### ISSUE TITLE
1.20.4 for Fzzy Config?

### ISSUE THREAD

**Issue by Tsunai001** [fzzyhmstrs/pc#14]
Particle Core fsr has 1.20.4 support which is basically useless without Fzzy Config; which doesnt have 1.20.4, assume you're working on this already? Cant have my modpack without your mod.

**Comment by fzzyhmstrs** [comment]
I do not have a planned 1.20.4 Fzzy Config version. 1.20.5/6 have better mod support and Fzzy Config and Particle core both exist for those versions.

**Comment by fzzyhmstrs** [comment]
I ended up creating a 1.20.4 version; so, happy surprise!

**Comment by Tsunai001** [comment]
Thank you so much
