### ISSUE TITLE
Can't open config screen

### ISSUE THREAD

**Issue by luciobortoletto** [fzzyhmstrs/pc#17]
Mods installed:
- Fabric API 0.100.7+1.21
- Fabric Language Kotlin 1.11.0+kotlin.2.0.00
- Fzzy Config 0.3.5+1.21
- Mod Menu 11.0.1
- Particle Core 0.2.3+1.21  
  
The game doesn't crash, I simply can't open the config screen.  
  
Logs: https://mclo.gs/I9zDJVm

**Comment by fzzyhmstrs** [comment]
Fixed in 0.2.4 (might still be processing on CF or Modrinth as of writing this comment.)
