### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by angeerey** [fzzyhmstrs/pc#2]
The newest version of this mod, Particle Core 0.1.2+1.20, is being detected as a virus by my Microsoft Defender.

**Comment by fzzyhmstrs** [comment]
This is an ongoing issue with *many* mod jars with the newest versions of Windows Defender falsely flagging them. Here's a random example from EMI

<img width="370" alt="image" src="https://github.com/fzzyhmstrs/pc/assets/72876796/a6e69048-8fb6-4b31-ae6a-963124b3e2b5">
