### ISSUE TITLE
Comparison between immediately fast and particle core ?

### ISSUE THREAD

**Issue by Beez3-A** [fzzyhmstrs/pc#23]
Both mods do improvements on particles, but what's the difference between them ?

**Comment by fzzyhmstrs** [comment]
Id have to review their source code to be absolutely sure, but my understanding of the basic difference is Particle Core optimizes "pre rendering" (culling particles that don't need to be drawn, optimizing 3D rotations, lightmap polling optimization, etc), while immediately fast optimizes the actual rendering of the particles that are drawn. I believe these two optimizations stack well

**Comment by Beez3-A** [comment]
Thanks for the lightspeed response :D
