### ISSUE TITLE
[Question & Bug?]: Culling Doesn't Really Cull???

### ISSUE THREAD

**Issue by Fyoncle** [fzzyhmstrs/pc#25]
So technically, when i turn around from particles they cull right, and gives me FPS, but even if i turn around it doesn't give too many FPS.

But if i disable all the particles in the config, now it gets me up to 500 FPS which is what it should be giving when they also culled isn't it?

I don't know much about culling so just curious.

**Comment by fzzyhmstrs** [comment]
With culling, the particles still exist abd all have to be checked for position versus the players view and passed over if they aren't in view (and rendered if they are).

The disable particles setting prevents any particles from spawning at all, so not only is there no rendering time, but no particles to tick, check for collisions, etc.

**Comment by Fyoncle** [comment]
> With culling, the particles still exist abd all have to be checked for position versus the players view and passed over if they aren't in view (and rendered if they are).
> 
> The disable particles setting prevents any particles from spawning at all, so not only is there no rendering time, but no particles to tick, check for collisions, etc.

Ah gotcha, thank you ❤️

Also is there any known incompatibility with optimization mods such as:

Sodium
Lithium
FerriteCore
Entity Culling
Indium
ImmediatelyFast
SodiumExtra
Reesee's Sodium Options
ModernFix
More Culling
Krypton
Ennhanced Block Entities
Debugify
C2ME
Noisium
Memory Leak Fix

**Comment by fzzyhmstrs** [comment]
There are no known issues with any of those mods

**Comment by Fyoncle** [comment]
> There are no known issues with any of those mods

Lovely! Am i allowed to have this mod for my modpack called [Elysium Days](https://modrinth.com/modpack/elysium-days) with giving credits on the modpack page?

**Comment by fzzyhmstrs** [comment]
yes, that would be ok

**Comment by Fyoncle** [comment]
> yes, that would be ok

Thanks! ❤️
