### ISSUE TITLE
[Feature Request] In-game Configuration

### ISSUE THREAD

**Issue by R00tB33rMan** [fzzyhmstrs/pc#3]
This mod is fantastic and immensely assists with particles (most notably, fireworks). That said, I feel as if an in-game configuration via mods such as ModMenu would be remarkably effective. This mod feels whole in every other way except with having an in-game configuration. Thank you for your extraordinarily hard work, and I hope you have time—this is a possibility!

**Comment by fzzyhmstrs** [comment]
Planned in the future once my new config lib is ready.

**Comment by fzzyhmstrs** [comment]
This is now available with PC 0.2.0 (currently only available on modrinth, CF to follow)

**Comment by R00tB33rMan** [comment]
> This is now available with PC 0.2.0 (currently only available on modrinth, CF to follow)

Only for 1.20-1.20.1?
