### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by obj-obj** [fzzyhmstrs/pc#5]
When shaders are enabled, particles don't render at all.

**Comment by fzzyhmstrs** [comment]
I can't replicate this:

https://github.com/fzzyhmstrs/pc/assets/72876796/86581867-9590-47ce-a309-c0d862f1a260

**Comment by obj-obj** [comment]
I'm using the iris distant horozons beta, maybe it's just an iris issue?

**Comment by obj-obj** [comment]
Fixed on 1.21
