### ISSUE TITLE
v0.2.3+1.20.1 not compatible with most recent QKL

### ISSUE THREAD

**Issue by Anarchick** [fzzyhmstrs/pc#9]
Particule Core v0.2.3 for 1.20.1 release on Apr 27 require at least 1.10.18+Kotlin 1.9.22 which is not available for mc 1.20.1

**Comment by fzzyhmstrs** [comment]
Download and use fabric language kotlin in that case. It works the exact same (QKL has no quilt specific function to my knowledge)
